spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ashab.project.bot@gmail.com
    password: tnul ibuw dmsb epjo
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  application:
    name: BankIt_backend
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/FREEPDB1
    username: BANKAPP
    password: ashab105
    driver-class-name: oracle.jdbc.OracleDriver
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.project.BankIt_backend.kafka_.event.TransactionCompletedEvent

logging:
  level:
    org:
      springframework:
        security: DEBUG